services:
  go-ethereum-satan:
    #image: c34044cdba98
    image: sboyadzhiev/go-etherium-satan-contract:latest
    #image: sha256:54a4856c2cb9402e7772769c3cc20e3585eedac2f5378f6347117401ecdd269f
    container_name: go-hell-contract
    ports:
      - "8545:8545"
      - "30303:30303"
    command: 
      #- --password=/root/password.txt
      #- --dev
      - --http
      - --http.addr=0.0.0.0
      #- --datadir=data
      # - --networkid=1337
      # - --http.port=8545
      # - --http.api=eth,net,web3
      # - --http.corsdomain=*
      # - --http.vhosts=*