name: ci_build

on:
    pull_request:
        types: 
        - closed        
    workflow_dispatch:

jobs:
  ci-build-on-merge:
    if: |
      github.event.pull_request.merged == true && 
      contains(github.event.pull_request.labels.*.name, 'CI:Build')
    runs-on: ubuntu-latest
    steps:
      # Pull the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}       

      # Build and push the image
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile          
          platforms: linux/amd64     
          push: true                  
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-etherium-satan:latest    

  ci-build-manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      # Pull the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4) Log in to Docker Hub – store secrets in repo → Settings → Secrets and variables → Actions
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the image
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile           
          platforms: linux/amd64      
          push: true                  
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-etherium-satan:latest 
          