name: CI_Deploy

on:
    pull_request:
        types: 
        - closed        
    workflow_dispatch:

jobs:
  CI-deploy-on-merge:
    if: |
      github.event.pull_request.merged == true && 
      contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    runs-on: ubuntu-latest
    steps:
      # Pull the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16 

      # Install Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Install docker compose  
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1       

      # Verify docker version
      - name: Docker Version 
        run: docker version 
      
      # Run ethereum node container  
      - name: Ethereum Node
        run: docker compose -p go-ethereum-hell -f docker-compose-hell.yml up -d

      # Upload contract by using hardhat task
      - name: Contract Upload
        #run: pwd
        run: |
          cd hardhat
          npm install
          npx hardhat compile
          npx hardhat deploy --network hell --unlock-time 1780166253

      # Create docker image from the container with the deployed contract
      - name: Docker commit
        run: docker commit go-ethereum-hell-node sboyadzhiev/go-etherium-satan-contract:latest 
       
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}     

      - name: Docker push
        run: docker image push sboyadzhiev/go-etherium-satan-contract:latest

  CI-deploy-manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      # Pull the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16 

      # Install Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Install docker compose  
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1       

      # Verify docker version
      - name: Docker Version 
        run: docker version 
      
      # Run ethereum node container  
      - name: Ethereum Node
        run: docker compose -p go-ethereum-hell -f docker-compose-hell.yml up -d

      # Upload contract by using hardhat task
      - name: Contract Upload
        #run: pwd
        run: |
          cd hardhat
          npm install
          npx hardhat compile
          npx hardhat deploy --network hell --unlock-time 1780166253

      # Create docker image from the container with the deployed contract
      - name: Docker commit
        run: docker commit go-ethereum-hell-node sboyadzhiev/go-etherium-satan-contract:latest 
       
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}     

      - name: Docker push
        run: docker image push sboyadzhiev/go-etherium-satan-contract:latest